M48
; DRILL file {KiCad (7.0.0)} date Tue May 23 17:02:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-23T17:02:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.6772Y-3.0709
T2
X2.0472Y-4.1339
X3.1496Y-3.1102
X4.252Y-4.9606
X6.2205Y-2.6772
T0
M30
